### ISSUE TITLE
home page >company overview section > mobile view and tablet content will be align middle. 

### ISSUE THREAD

**Issue by NexGenSoft750** [NexGenSoft750/nexgen_soft#11]
@Maqsood-Ahmad-72 plz align content in center on mobile and tablet screen.
![Uploading Screenshot_4.png…]()

**Comment by talha-sajjad-dev** [comment]
@Maqsood-Ahmad-72, I noticed that the actual issue with tabs buttons no need full background color just place border bottom and remove full background color. Let me know if you have any question.   
![image](https://github.com/user-attachments/assets/332197c2-fa88-4b34-a738-14eecd3602ca)

**Comment by talha-sajjad-dev** [comment]
For Reference Do same like that  Click on this [Link](https://block.codescandy.com/landing-it-company.html)
![image](https://github.com/user-attachments/assets/a63b5855-da10-47d4-b981-0b362e7a9951)
